---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-bench
spec:
  completions: 2      
  parallelism: 2
  template:
    metadata:
      labels:
        app: kube-bench  # ← Thêm label này
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app  # ← Đổi thành "app"
                operator: In
                values:
                - kube-bench
            topologyKey: kubernetes.io/hostname
      hostPID: true
      containers:
      - name: kube-bench
        image: docker.io/aquasec/kube-bench:v0.13.0
        command:
          - kube-bench
          - run
          - --targets
          - node
          - --benchmark
          - aks-1.7
        volumeMounts:
          - name: var-lib-kubelet
            mountPath: /var/lib/kubelet
            readOnly: true
          - name: etc-systemd
            mountPath: /etc/systemd
            readOnly: true
          - name: etc-default
            mountPath: /etc/default
            readOnly: true
          - name: etc-kubernetes
            mountPath: /etc/kubernetes
            readOnly: true
      restartPolicy: Never
      volumes:
        - name: var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: etc-systemd
          hostPath:
            path: /etc/systemd
        - name: etc-default
          hostPath:
            path: /etc/default
        - name: etc-kubernetes
          hostPath:
            path: /etc/kubernetes