create table course (begin_date date, begin_shift integer, day_of_week integer, end_date date, end_shift integer, id integer not null auto_increment, main_course_id integer, registered_number integer, semester_id integer, subject_id integer, total_number integer, week_distance integer, course_id varchar(255), language varchar(255), lecturer_name varchar(255), room varchar(255), primary key (id)) engine=InnoDB;
create table registration (course_id integer not null, result bit, student_id integer not null, primary key (course_id, student_id)) engine=InnoDB;
create table registration_period (id integer not null auto_increment, semester_id integer, close_time datetime(6), open_time datetime(6), primary key (id)) engine=InnoDB;
create table role (id integer not null auto_increment, role_name varchar(255), primary key (id)) engine=InnoDB;
create table semester (id integer not null auto_increment, semester_num integer, year integer, primary key (id)) engine=InnoDB;
create table student (id integer not null auto_increment, khoa_tuyen integer, user_id integer not null, falcuty_name varchar(255), program varchar(255), primary key (id)) engine=InnoDB;
create table subject (id integer not null auto_increment, practice_credit_number integer, theory_credit_number integer, subject_id varchar(255), subject_name varchar(255), primary key (id)) engine=InnoDB;
create table subject_relation (curr_subject_id integer not null, pre_subject_id integer not null, type integer, primary key (curr_subject_id, pre_subject_id)) engine=InnoDB;
create table user (id integer not null auto_increment, role_id integer not null, email varchar(255) not null, name varchar(255), password varchar(255), user_id varchar(255), primary key (id)) engine=InnoDB;
alter table course add constraint UK_tckrkcy5xdlahye20nppf6i1l unique (course_id);
alter table student add constraint UK_bkix9btnoi1n917ll7bplkvg5 unique (user_id);
alter table user add constraint UK_ob8kqyqqgmefl0aco34akdtpe unique (email);
alter table course add constraint FKmbr38vd0ju01t2oqerncstlph foreign key (main_course_id) references course (id);
alter table course add constraint FKlmyb73uymsfhqh374ndr3n4c0 foreign key (semester_id) references semester (id);
alter table course add constraint FKm1expnaas0onmafqpktmjixnx foreign key (subject_id) references subject (id);
alter table registration add constraint FKo0ifq05dge7ssg2voqs6wtik6 foreign key (course_id) references course (id);
alter table registration add constraint FKcxvegulu1x4mjcvy3116tu5xu foreign key (student_id) references student (id);
alter table registration_period add constraint FKb02antaqgp5wrtq71yvh3d2mh foreign key (semester_id) references semester (id);
alter table student add constraint FKk5m148xqefonqw7bgnpm0snwj foreign key (user_id) references user (id);
alter table subject_relation add constraint FKogjeox0uf7yoijpqr8gmtexil foreign key (curr_subject_id) references subject (id);
alter table subject_relation add constraint FK3l6b64f8qg6bp18j2k3c37e1f foreign key (pre_subject_id) references subject (id);
alter table user add constraint FKn82ha3ccdebhokx3a8fgdqeyy foreign key (role_id) references role (id);